import os 

# General
def convert_list_to_string(list):
    returnstring = ""
    for listval in list:
        returnstring = returnstring+listval+", "
    returnstring = returnstring[:-2]
    return returnstring

def delete_script_file(script_file_name):
    if os.path.exists(script_file_name):
        os.remove(script_file_name)

def write_cmd_to_script_file(script, script_file_name):
    delete_script_file(script_file_name)
    script_file_name = open(script_file_name, "a")
    for line in script:
        script_file_name.writelines(line+'\n')
    script_file_name.close()

# Custom 
def get_validate_vcf_md_script(vcf_json_py):
    markdown_script = []
    mdline = "# VCF 5.2 Configuration Validation"
    markdown_script.append(mdline)
    mdline = ("The following values were pulled from the vcf.json file that will be used during VCF Bringup.")
    markdown_script.append(mdline)
    mdline = ("")
    markdown_script.append(mdline)
    mdline = ("## General")
    markdown_script.append(mdline)
    mdline = ("| Parameter | Configured Value |")
    markdown_script.append(mdline)
    mdline = ("|-----------|------------------|")
    markdown_script.append(mdline)
    mdline = ("| dvSwitch Version | "+vcf_json_py["dvSwitchVersion"]+" |")
    markdown_script.append(mdline)
    mdline = ("| Management Pool Name | "+vcf_json_py["managementPoolName"]+" |")
    markdown_script.append(mdline)
    mdline = ("| SDDC ID | "+vcf_json_py["sddcId"]+" |")
    markdown_script.append(mdline)
    mdline = ("")
    markdown_script.append(mdline)
    mdline = ("## License Keys")
    markdown_script.append(mdline)
    mdline = ("| Parameter | Configured Value |")
    markdown_script.append(mdline)
    mdline = ("|-----------|------------------|")
    markdown_script.append(mdline)
    mdline = ("| ESXi License Key | "+vcf_json_py["esxLicense"]+" |")
    markdown_script.append(mdline)
    mdline = ("| vCenter License Key | "+vcf_json_py["vcenterSpec"]["licenseFile"]+" |")
    markdown_script.append(mdline)
    mdline = ("| vSAN License Key | "+vcf_json_py["vsanSpec"]["licenseFile"]+" |")
    markdown_script.append(mdline)
    mdline = ("| NSX License Key | "+vcf_json_py["nsxtSpec"]["nsxtLicense"]+" |")
    markdown_script.append(mdline)
    mdline = ("")
    markdown_script.append(mdline)
    mdline = ("## Credentials")
    markdown_script.append(mdline)
    mdline = ("| Parameter | Configured Value |")
    markdown_script.append(mdline)
    mdline = ("|-----------|------------------|")
    markdown_script.append(mdline)
    mdline = ("| SDDC Manager Local User Password | "+vcf_json_py["sddcManagerSpec"]["localUserPassword"]+" |")
    markdown_script.append(mdline)
    mdline = ("| SDDC Manager Root User Username | "+vcf_json_py["sddcManagerSpec"]["rootUserCredentials"]["username"]+" |")
    markdown_script.append(mdline)
    mdline = ("| SDDC Manager Root User Password | "+vcf_json_py["sddcManagerSpec"]["rootUserCredentials"]["password"]+" |")
    markdown_script.append(mdline)
    mdline = ("| SDDC Manager Second User Username | "+vcf_json_py["sddcManagerSpec"]["secondUserCredentials"]["username"]+" |")
    markdown_script.append(mdline)
    mdline = ("| SDDC Manager Second User Password | "+vcf_json_py["sddcManagerSpec"]["secondUserCredentials"]["password"]+" |")
    markdown_script.append(mdline)
    mdline = ("| root NSX Manager Password | "+vcf_json_py["nsxtSpec"]["rootNsxtManagerPassword"]+" |")
    markdown_script.append(mdline)
    mdline = ("| NSX Admin Password | "+vcf_json_py["nsxtSpec"]["nsxtAdminPassword"]+" |")
    markdown_script.append(mdline)
    mdline = ("| NSX Audit Password | "+vcf_json_py["nsxtSpec"]["nsxtAuditPassword"]+" |")
    markdown_script.append(mdline)
    psc_count = len(vcf_json_py["pscSpecs"])
    i=0
    while i < psc_count:
        mdline = ("| Platform Services Controller "+str(i+1)+" Admin User SSO Password | "+vcf_json_py["pscSpecs"][i]["adminUserSsoPassword"]+" |")
        markdown_script.append(mdline)
        i = i+1
    mdline = ("| vCenter Root Password | "+vcf_json_py["vcenterSpec"]["rootVcenterPassword"]+" |")
    markdown_script.append(mdline)
    esxi_host_count = len(vcf_json_py["hostSpecs"])
    i = 0 
    while i < esxi_host_count:
        mdline = ("| ESXi Host "+str(i+1)+" Username | "+vcf_json_py["hostSpecs"][i]["credentials"]["username"]+" |")
        markdown_script.append(mdline)
        mdline = ("| ESXi Host "+str(i+1)+" Password | "+vcf_json_py["hostSpecs"][i]["credentials"]["password"]+" |")
        markdown_script.append(mdline)
        i=i+1
    mdline = ("")
    markdown_script.append(mdline)
    mdline = ("## Network Specs")
    markdown_script.append(mdline)
    mdline = ("| Network Type | Subnet | VLAN ID | MTU | Gateway |")
    markdown_script.append(mdline)
    mdline = ("|--------------|--------|---------|-----|---------|")
    markdown_script.append(mdline)
    network_count = len(vcf_json_py["networkSpecs"])
    i=0
    while i < network_count:
        mdline = ("| "+vcf_json_py["networkSpecs"][i]["networkType"]+" | "+vcf_json_py["networkSpecs"][i]["subnet"]+" | "+vcf_json_py["networkSpecs"][i]["mtu"]+" | "+vcf_json_py["networkSpecs"][i]["gateway"])
        markdown_script.append(mdline)
        i=i+1
    mdline = ("")
    markdown_script.append(mdline)
    mdline = ("| Network Type | Include IP Address Range (Start) | Include IP Address Range (End) |")
    markdown_script.append(mdline)
    mdline = ("|---|---|---|")
    markdown_script.append(mdline)
    vsan_included_ip_count = len(vcf_json_py["networkSpecs"][1]["includeIpAddressRanges"])
    i=0 
    while i < vsan_included_ip_count:
        mdline = ("| VSAN | "+vcf_json_py["networkSpecs"][1]["includeIpAddressRanges"][i]["startIpAddress"]+" | "+vcf_json_py["networkSpecs"][1]["includeIpAddressRanges"][i]["endIpAddress"])
        markdown_script.append(mdline)
        i=i+1
    vmotion_included_ip_count = len(vcf_json_py["networkSpecs"][2]["includeIpAddressRanges"])
    i=0 
    while i < vmotion_included_ip_count:
        mdline = ("| VMOTION | "+vcf_json_py["networkSpecs"][2]["includeIpAddressRanges"][i]["startIpAddress"]+" | "+vcf_json_py["networkSpecs"][1]["includeIpAddressRanges"][i]["endIpAddress"])
        markdown_script.append(mdline)
        i=i+1
    mdline = ("")
    markdown_script.append(mdline)
    mdline = ("| Network Type | Include IP Address |")
    markdown_script.append(mdline)
    mdline = ("|---|---|")
    markdown_script.append(mdline)
    vsan_included_ip_count = len(vcf_json_py["networkSpecs"][1]["includeIpAddress"])
    i=0 
    while i < vsan_included_ip_count:
        mdline = ("| VSAN | "+vcf_json_py["networkSpecs"][1]["includeIpAddress"][i]+" |")
        markdown_script.append(mdline)
        i=i+1
    mdline = ("")
    markdown_script.append(mdline)
    mdline = ("## Domain Specs")
    markdown_script.append(mdline)
    mdline = ("| Parameter | Configured Value |")
    markdown_script.append(mdline)
    mdline = ("|-----------|------------------|")
    markdown_script.append(mdline)
    ntp_servers = convert_list_to_string(vcf_json_py["ntpServers"])
    mdline = ("| NTP Servers | "+ntp_servers+" |")
    markdown_script.append(mdline)
    mdline = ("| Subdomain | "+vcf_json_py["dnsSpec"]["subdomain"]+" |")
    markdown_script.append(mdline)
    mdline = ("| Domain | "+vcf_json_py["dnsSpec"]["domain"]+" |")
    markdown_script.append(mdline)
    mdline = ("| Name Server | "+vcf_json_py["dnsSpec"]["nameserver"]+" |")
    markdown_script.append(mdline)
    mdline = ("| Secondary Name Server | "+vcf_json_py["dnsSpec"]["secondaryNameserver"]+" |")
    markdown_script.append(mdline)
    mdline = ("")
    markdown_script.append(mdline)
    mdline = ("## DNS Entries")
    markdown_script.append(mdline)
    mdline = ("| Parameter | Hostname | IP Address |")
    markdown_script.append(mdline)
    mdline = ("|-----------|----------|------------|")
    markdown_script.append(mdline)
    mdline = ("| SDDC Manager | "+vcf_json_py["sddcManagerSpec"]["hostname"]+" | "+vcf_json_py["sddcManagerSpec"]["ipAddress"]+" |")
    markdown_script.append(mdline)
    nsx_managers_count = len(vcf_json_py["nsxtSpec"]["nsxtManagers"])
    i=0
    while i < nsx_managers_count:
        mdline = ("| NSX Manager "+str(i+1)+" | "+vcf_json_py["nsxtSpec"]["nsxtManagers"][i]["hostname"]+" | "+vcf_json_py["nsxtSpec"]["nsxtManagers"][i]["ip"]+" |")
        markdown_script.append(mdline)
        i=i+1

    markdown_script.append(mdline)
    mdline = ("| NSX Manager VIP | "+vcf_json_py["nsxtSpec"]["vipFqdn"]+" | "+vcf_json_py["nsxtSpec"]["vip"]+" |")
    markdown_script.append(mdline)
    mdline = ("| vCenter | "+vcf_json_py["vcenterSpec"]["vcenterHostname"]+" | "+vcf_json_py["vcenterSpec"]["vcenterIp"]+" |")
    markdown_script.append(mdline)
    esxi_host_count = len(vcf_json_py["hostSpecs"])
    i = 0 
    while i < esxi_host_count:
        mdline = ("| ESXi Host "+str(i+1)+" | "+vcf_json_py["hostSpecs"][i]["hostname"]+" | "+vcf_json_py["hostSpecs"][i]["ipAddressPrivate"]["ipAddress"]+" |")
        markdown_script.append(mdline)
        i=i+1

    mdline = ("")
    markdown_script.append(mdline)
    mdline = ("## NSXT Specs")
    markdown_script.append(mdline)
    mdline = ("| Parameter | Configured Value |")
    markdown_script.append(mdline)
    mdline = ("|-----------|------------------|")
    markdown_script.append(mdline)
    mdline = ("| NSX Manager Size | "+vcf_json_py["nsxtSpec"]["nsxtManagerSize"]+" |")
    markdown_script.append(mdline)
    mdline = ("| Overlay Transport Zone Name | "+vcf_json_py["nsxtSpec"]["overLayTransportZone"]["zoneName"]+" |")
    markdown_script.append(mdline)
    mdline = ("| Overlay Transport Network Name | "+vcf_json_py["nsxtSpec"]["overLayTransportZone"]["networkName"]+" |")
    markdown_script.append(mdline)
    mdline = ("| VLAN Transport Zone Name | "+vcf_json_py["nsxtSpec"]["vlanTransportZone"]["zoneName"]+" |")
    markdown_script.append(mdline)
    mdline = ("| VLAN Transport Network Name | "+vcf_json_py["nsxtSpec"]["vlanTransportZone"]["networkName"]+" |")
    markdown_script.append(mdline)
    mdline = ("")
    markdown_script.append(mdline)
    mdline = ("## SDDC Manager Specs")
    markdown_script.append(mdline)
    mdline = ("| Parameter | Configured Value |")
    markdown_script.append(mdline)
    mdline = ("|-----------|------------------|")
    markdown_script.append(mdline)
    mdline = ("| Netmask   | "+vcf_json_py["sddcManagerSpec"]["netmask"]+" |")
    markdown_script.append(mdline)
    mdline = ("")
    markdown_script.append(mdline)
    mdline = ("## VSAN Specs")
    markdown_script.append(mdline)
    mdline = ("| Parameter | Configured Value |")
    markdown_script.append(mdline)
    mdline = ("|-----------|------------------|")
    markdown_script.append(mdline)
    mdline = ("| vSAN Name | "+vcf_json_py["vsanSpec"]["vsanName"]+" |")
    markdown_script.append(mdline)
    mdline = ("| Datastore Name | "+vcf_json_py["vsanSpec"]["datastoreName"]+" |")
    markdown_script.append(mdline)
    mdline = ("")
    markdown_script.append(mdline)
    mdline = ("## Distributed Virtual Switch Specs")
    markdown_script.append(mdline)
    mdline = ("| Parameter | Configured Value |")
    markdown_script.append(mdline)
    mdline = ("|-----------|------------------|")
    markdown_script.append(mdline)
    dvs_spec_count = len(vcf_json_py["dvsSpecs"])
    i=0
    while i < dvs_spec_count:
        mdline = ("| DVS "+str(i+1)+" Name | "+str(vcf_json_py["dvsSpecs"][i]["dvsName"])+" |")
        markdown_script.append(mdline)
        mdline = ("| MTU | "+str(vcf_json_py["dvsSpecs"][i]["mtu"])+" |")
        markdown_script.append(mdline)
        nioc_spec_count = len(vcf_json_py["dvsSpecs"][i]["niocSpecs"])
        y=0
        while y < nioc_spec_count:
            mdline = "| Traffic Type | "+vcf_json_py["dvsSpecs"][i]["niocSpecs"][y]["trafficType"]+" ("+vcf_json_py["dvsSpecs"][i]["niocSpecs"][y]["value"]+") |"
            markdown_script.append(mdline)
            y=y+1
        dvs_networks = convert_list_to_string(vcf_json_py["dvsSpecs"][i]["networks"])
        mdline = ("| Networks | "+dvs_networks+" |")
        markdown_script.append(mdline)
        i=i+1
    mdline = ("")
    markdown_script.append(mdline)
    mdline = ("## ESXi Cluster Specs")
    markdown_script.append(mdline)
    mdline = ("| Parameter | Configured Value |")
    markdown_script.append(mdline)
    mdline = ("|-----------|------------------|")
    markdown_script.append(mdline)
    mdline = ("| Cluster Name | "+vcf_json_py["clusterSpec"]["clusterName"]+" |")
    markdown_script.append(mdline)
    mdline = ("| Cluster EVC Mode | "+vcf_json_py["clusterSpec"]["clusterEvcMode"]+" |")
    markdown_script.append(mdline)
    mdline = ("| Resource Pool Specs: |  |")
    markdown_script.append(mdline)
    resource_pool_spec_count = len(vcf_json_py["clusterSpec"]["resourcePoolSpecs"])
    i=0
    while i < resource_pool_spec_count:
        # Unecessary customization to fix silly shennanigans in this json structure
        # Please ask VMware VCF BU to keep resourcePoolSpecs consistent
        if i == 3:
            mdline = ("| Resource Pool "+str(i+1)+" Name | "+vcf_json_py["clusterSpec"]["resourcePoolSpecs"][i]["name"]+" |")
            markdown_script.append(mdline)
            mdline = ("| Resource Pool "+str(i+1)+" Type | "+vcf_json_py["clusterSpec"]["resourcePoolSpecs"][i]["type"]+" |")
            markdown_script.append(mdline)
            mdline = ("| Resource Pool "+str(i+1)+" CPU Reservation Mhz | "+str(vcf_json_py["clusterSpec"]["resourcePoolSpecs"][i]["cpuReservationMhz"])+" |")
            markdown_script.append(mdline)
            mdline = ("| Resource Pool "+str(i+1)+" CPU Limit | "+str(vcf_json_py["clusterSpec"]["resourcePoolSpecs"][i]["cpuLimit"])+" |")
            markdown_script.append(mdline)
            mdline = ("| Resource Pool "+str(i+1)+" CPU Reservation Expandable | "+str(vcf_json_py["clusterSpec"]["resourcePoolSpecs"][i]["cpuReservationExpandable"])+" |")
            markdown_script.append(mdline)
            mdline = ("| Resource Pool "+str(i+1)+" CPU Shares Level | "+str(vcf_json_py["clusterSpec"]["resourcePoolSpecs"][i]["cpuSharesLevel"])+" |")
            markdown_script.append(mdline)
            mdline = ("| Resource Pool "+str(i+1)+" Memory Reservation MB | "+str(vcf_json_py["clusterSpec"]["resourcePoolSpecs"][i]["memoryReservationMb"])+" |")
            markdown_script.append(mdline)
            mdline = ("| Resource Pool "+str(i+1)+" Memory Reservation Expandable | "+str(vcf_json_py["clusterSpec"]["resourcePoolSpecs"][i]["memoryReservationExpandable"])+" |")
            markdown_script.append(mdline)
            mdline = ("| Resource Pool "+str(i+1)+" Memory Shares Level | "+str(vcf_json_py["clusterSpec"]["resourcePoolSpecs"][i]["memorySharesLevel"])+" |")
            markdown_script.append(mdline)
            mdline = ("| Resource Pool "+str(i+1)+" Memory Shares Value | "+str(vcf_json_py["clusterSpec"]["resourcePoolSpecs"][i]["memorySharesValue"])+" |")
            markdown_script.append(mdline)
        else:
            mdline = ("| Resource Pool "+str(i+1)+" Name | "+vcf_json_py["clusterSpec"]["resourcePoolSpecs"][i]["name"]+" |")
            markdown_script.append(mdline)
            mdline = ("| Resource Pool "+str(i+1)+" CPU Shares Level | "+vcf_json_py["clusterSpec"]["resourcePoolSpecs"][i]["cpuSharesLevel"]+" |")
            markdown_script.append(mdline)
            mdline = ("| Resource Pool "+str(i+1)+" CPU Shares Value | "+str(vcf_json_py["clusterSpec"]["resourcePoolSpecs"][i]["cpuSharesLevel"])+" |")
            markdown_script.append(mdline)
            mdline = ("| Resource Pool "+str(i+1)+" CPU Limit | "+str(vcf_json_py["clusterSpec"]["resourcePoolSpecs"][i]["cpuLimit"])+" |")
            markdown_script.append(mdline)
            mdline = ("| Resource Pool "+str(i+1)+" CPU Reservation Percentage | "+str(vcf_json_py["clusterSpec"]["resourcePoolSpecs"][i]["cpuReservationPercentage"])+" |")
            markdown_script.append(mdline)
            mdline = ("| Resource Pool "+str(i+1)+" CPU Reservation Expandable | "+str(vcf_json_py["clusterSpec"]["resourcePoolSpecs"][i]["cpuReservationExpandable"])+" |")
            markdown_script.append(mdline)
            mdline = ("| Resource Pool "+str(i+1)+" Memory Shares Level | "+str(vcf_json_py["clusterSpec"]["resourcePoolSpecs"][i]["memorySharesLevel"])+" |")
            markdown_script.append(mdline)
            mdline = ("| Resource Pool "+str(i+1)+" Memory Shares Value | "+str(vcf_json_py["clusterSpec"]["resourcePoolSpecs"][i]["memorySharesValue"])+" |")
            markdown_script.append(mdline)
            mdline = ("| Resource Pool "+str(i+1)+" Memory Limit | "+str(vcf_json_py["clusterSpec"]["resourcePoolSpecs"][i]["memoryLimit"])+" |")
            markdown_script.append(mdline)
            mdline = ("| Resource Pool "+str(i+1)+" Memory Reservation Percentage | "+str(vcf_json_py["clusterSpec"]["resourcePoolSpecs"][i]["memoryReservationPercentage"])+" |")
            markdown_script.append(mdline)
            mdline = ("| Resource Pool "+str(i+1)+" Memory Reservation Expandable | "+str(vcf_json_py["clusterSpec"]["resourcePoolSpecs"][i]["memoryReservationExpandable"])+" |")
            markdown_script.append(mdline)
        i=i+1

    mdline = ("")
    markdown_script.append(mdline)
    mdline = ("## Platform Services Controller Specs")
    markdown_script.append(mdline)
    mdline = ("| Parameter | Configured Value |")
    markdown_script.append(mdline)
    mdline = ("|-----------|------------------|")
    markdown_script.append(mdline)
    psc_count = len(vcf_json_py["pscSpecs"])
    i=0 
    while i < psc_count:
        mdline = ("| PSC "+str(i+1)+" ID | "+vcf_json_py["pscSpecs"][i]["pscId"]+" |")
        markdown_script.append(mdline)
        mdline = ("| PSC "+str(i+1)+" SSO Domain | "+vcf_json_py["pscSpecs"][i]["pscSsoSpec"]["ssoDomain"]+" |")
        markdown_script.append(mdline)
        i=i+1

    mdline = ("")
    markdown_script.append(mdline)
    mdline = ("## vCenter Spec")
    markdown_script.append(mdline)
    mdline = ("| Parameter | Configured Value |")
    markdown_script.append(mdline)
    mdline = ("|-----------|------------------|")
    markdown_script.append(mdline)
    mdline = ("| VM Size | "+vcf_json_py["vcenterSpec"]["vmSize"]+" |")
    markdown_script.append(mdline)
    mdline = ("")
    markdown_script.append(mdline)
    mdline = ("## ESXi Host Specs")
    markdown_script.append(mdline)
    mdline = ("| Server ID | Hostname | Association | vSwitch | Subnet Mask | CIDR | Gateway | IP Address |")
    markdown_script.append(mdline)
    mdline = ("|-----------|----------|-------------|---------|-------------|------|---------|------------|")
    markdown_script.append(mdline)
    esxi_host_count = len(vcf_json_py["hostSpecs"])
    i = 0 
    while i < esxi_host_count:
        mdline = ("| "+vcf_json_py["hostSpecs"][i]["serverId"]+" | "+vcf_json_py["hostSpecs"][i]["hostname"]+" | "+vcf_json_py["hostSpecs"][i]["association"]+" | "+vcf_json_py["hostSpecs"][i]["vSwitch"]+" | "+vcf_json_py["hostSpecs"][i]["ipAddressPrivate"]["subnet"]+" | "+vcf_json_py["hostSpecs"][i]["ipAddressPrivate"]["cidr"]+" | "+vcf_json_py["hostSpecs"][i]["ipAddressPrivate"]["gateway"]+" | "+vcf_json_py["hostSpecs"][i]["ipAddressPrivate"]["ipAddress"]+" |")
        markdown_script.append(mdline)
        i=i+1 
    return markdown_script