import os 

# General
def delete_script_file(script_file_name):
    if os.path.exists(script_file_name):
        os.remove(script_file_name)

def write_cmd_to_script_file(script, script_file_name):
    delete_script_file(script_file_name)
    script_file_name = open(script_file_name, "a")
    for line in script:
        script_file_name.writelines(line+'\n')
    script_file_name.close()

# Custom 
def get_validate_vcf_md_script(vcf_json_py):
    markdown_script = []
    mdline = "# VCF 5.2 Configuration Validation"
    markdown_script.append(mdline)
    mdline = ("The following values were pulled from the vcf.json file that will be used during VCF Bringup.")
    markdown_script.append(mdline)
    mdline = ("")
    markdown_script.append(mdline)
    mdline = ("## General")
    markdown_script.append(mdline)
    mdline = ("| Parameter | Configured Value |")
    markdown_script.append(mdline)
    mdline = ("|-----------|------------------|")
    markdown_script.append(mdline)
    mdline = ("| dvSwitch Version | "+vcf_json_py["dvSwitchVersion"]+" |")
    markdown_script.append(mdline)
    mdline = ("| Management Pool Name | "+vcf_json_py["managementPoolName"]+" |")
    markdown_script.append(mdline)
    mdline = ("| SDDC ID | "+vcf_json_py["sddcId"]+" |")
    markdown_script.append(mdline)
    mdline = ("")
    markdown_script.append(mdline)
    mdline = ("## License Keys")
    markdown_script.append(mdline)
    mdline = ("| Parameter | Configured Value |")
    markdown_script.append(mdline)
    mdline = ("|-----------|------------------|")
    markdown_script.append(mdline)
    mdline = ("| ESXi License Key | "+vcf_json_py["esxLicense"]+" |")
    markdown_script.append(mdline)
    mdline = ("| vCenter License Key | "+vcf_json_py["vcenterSpec"]["licenseFile"]+" |")
    markdown_script.append(mdline)
    mdline = ("| vSAN License Key | "+vcf_json_py["vsanSpec"]["licenseFile"]+" |")
    markdown_script.append(mdline)
    mdline = ("| NSX License Key | "+vcf_json_py["nsxtSpec"]["nsxtLicense"]+" |")
    markdown_script.append(mdline)
    mdline = ("")
    markdown_script.append(mdline)
    mdline = ("## Credentials")
    markdown_script.append(mdline)
    mdline = ("| Parameter | Configured Value |")
    markdown_script.append(mdline)
    mdline = ("|-----------|------------------|")
    markdown_script.append(mdline)
    mdline = ("| SDDC Manager Local User Password | "+vcf_json_py["sddcManagerSpec"]["localUserPassword"]+" |")
    markdown_script.append(mdline)
    mdline = ("| SDDC Manager Root User Username | "+vcf_json_py["sddcManagerSpec"]["rootUserCredentials"]["username"]+" |")
    markdown_script.append(mdline)
    mdline = ("| SDDC Manager Root User Password | "+vcf_json_py["sddcManagerSpec"]["rootUserCredentials"]["password"]+" |")
    markdown_script.append(mdline)
    mdline = ("| SDDC Manager Second User Username | "+vcf_json_py["sddcManagerSpec"]["secondUserCredentials"]["username"]+" |")
    markdown_script.append(mdline)
    mdline = ("| SDDC Manager Second User Password | "+vcf_json_py["sddcManagerSpec"]["secondUserCredentials"]["password"]+" |")
    markdown_script.append(mdline)
    mdline = ("| root NSX Manager Password | "+vcf_json_py["nsxtSpec"]["rootNsxtManagerPassword"]+" |")
    markdown_script.append(mdline)
    mdline = ("| NSX Admin Password | "+vcf_json_py["nsxtSpec"]["nsxtAdminPassword"]+" |")
    markdown_script.append(mdline)
    mdline = ("| NSX Audit Password | "+vcf_json_py["nsxtSpec"]["nsxtAuditPassword"]+" |")
    markdown_script.append(mdline)
    psc_count = len(vcf_json_py["pscSpecs"])
    i=0
    while i < psc_count:
        mdline = ("| Platform Services Controller "+str(i+1)+" Admin User SSO Password | "+vcf_json_py["pscSpecs"][i]["adminUserSsoPassword"]+" |")
        markdown_script.append(mdline)
        i = i+1
    mdline = ("| vCenter Root Password | "+vcf_json_py["vcenterSpec"]["rootVcenterPassword"]+" |")
    markdown_script.append(mdline)
    esxi_host_count = len(vcf_json_py["hostSpecs"])
    i = 0 
    while i < esxi_host_count:
        mdline = ("| ESXi Host "+str(i+1)+" Username | "+vcf_json_py["hostSpecs"][i]["credentials"]["username"]+" |")
        markdown_script.append(mdline)
        mdline = ("| ESXi Host "+str(i+1)+" Password | "+vcf_json_py["hostSpecs"][i]["credentials"]["password"]+" |")
        markdown_script.append(mdline)
        i=i+1
    mdline = ("")
    markdown_script.append(mdline)
    mdline = ("## Network Specs")
    markdown_script.append(mdline)
    mdline = ("| Network Type | Subnet | VLAN ID | MTU | Gateway |")
    markdown_script.append(mdline)
    mdline = ("|--------------|--------|---------|-----|---------|")
    markdown_script.append(mdline)
    network_count = len(vcf_json_py["networkSpecs"])
    i=0
    while i < network_count:
        mdline = ("| "+vcf_json_py["networkSpecs"][i]["networkType"]+" | "+vcf_json_py["networkSpecs"][i]["subnet"]+" | "+vcf_json_py["networkSpecs"][i]["mtu"]+" | "+vcf_json_py["networkSpecs"][i]["gateway"])
        markdown_script.append(mdline)
        i=i+1
    mdline = ("")
    markdown_script.append(mdline)
    mdline = ("| Network Type | Include IP Address Range (Start) | Include IP Address Range (End) |")
    markdown_script.append(mdline)
    mdline = ("|---|---|---|")
    markdown_script.append(mdline)
    vsan_included_ip_count = len(vcf_json_py["networkSpecs"][1]["includeIpAddressRanges"])
    i=0 
    while i < vsan_included_ip_count:
        mdline = ("| VSAN | "+vcf_json_py["networkSpecs"][1]["includeIpAddressRanges"][i]["startIpAddress"]+" | "+vcf_json_py["networkSpecs"][1]["includeIpAddressRanges"][i]["endIpAddress"])
        markdown_script.append(mdline)
        i=i+1
    vmotion_included_ip_count = len(vcf_json_py["networkSpecs"][2]["includeIpAddressRanges"])
    i=0 
    while i < vmotion_included_ip_count:
        mdline = ("| VMOTION | "+vcf_json_py["networkSpecs"][2]["includeIpAddressRanges"][i]["startIpAddress"]+" | "+vcf_json_py["networkSpecs"][1]["includeIpAddressRanges"][i]["endIpAddress"])
        markdown_script.append(mdline)
        i=i+1
    mdline = ("")
    markdown_script.append(mdline)
    mdline = ("| Network Type | Include IP Address |")
    markdown_script.append(mdline)
    mdline = ("|---|---|")
    markdown_script.append(mdline)
    vsan_included_ip_count = len(vcf_json_py["networkSpecs"][1]["includeIpAddress"])
    i=0 
    while i < vsan_included_ip_count:
        mdline = ("| VSAN | "+vcf_json_py["networkSpecs"][1]["includeIpAddress"][i]+" |")
        markdown_script.append(mdline)
        i=i+1
    mdline = ("")
    markdown_script.append(mdline)
    mdline = ("## Domain Specs")
    markdown_script.append(mdline)
    mdline = ("| Parameter | Configured Value |")
    markdown_script.append(mdline)
    mdline = ("|-----------|------------------|")
    markdown_script.append(mdline)
    mdline = ("| NTP Servers |  |")
    markdown_script.append(mdline)
    mdline = ("| Subdomain |  |")
    markdown_script.append(mdline)
    mdline = ("| Domain |  |")
    markdown_script.append(mdline)
    mdline = ("| Name Server |  |")
    markdown_script.append(mdline)
    mdline = ("| Secondary Name Server |  |")
    markdown_script.append(mdline)
    mdline = ("")
    markdown_script.append(mdline)
    mdline = ("## DNS Entries")
    markdown_script.append(mdline)
    mdline = ("| Parameter | Hostname | IP Address |")
    markdown_script.append(mdline)
    mdline = ("|-----------|----------|------------|")
    markdown_script.append(mdline)
    mdline = ("| SDDC Manager |  |  |")
    markdown_script.append(mdline)
    mdline = ("| NSX Manager A |  |  |")
    markdown_script.append(mdline)
    mdline = ("| NSX Manager B |  |  |")
    markdown_script.append(mdline)
    mdline = ("| NSX Manager C |  |  |")
    markdown_script.append(mdline)
    mdline = ("| NSX Manager VIP |  |  |")
    markdown_script.append(mdline)
    mdline = ("| vCenter |  |  |")
    markdown_script.append(mdline)
    mdline = ("| ESXi Host 1 |  |  |")
    markdown_script.append(mdline)
    mdline = ("| ESXi Host 2 |  |  |")
    markdown_script.append(mdline)
    mdline = ("| ESXi Host 3 |  |  |")
    markdown_script.append(mdline)
    mdline = ("| ESXi Host 4 |  |  |")
    markdown_script.append(mdline)
    mdline = ("")
    markdown_script.append(mdline)
    mdline = ("## NSXT Specs")
    markdown_script.append(mdline)
    mdline = ("| Parameter | Configured Value |")
    markdown_script.append(mdline)
    mdline = ("|-----------|------------------|")
    markdown_script.append(mdline)
    mdline = ("| NSX Manager Size |  |")
    markdown_script.append(mdline)
    mdline = ("| Overlay Transport Zone Name |  |")
    markdown_script.append(mdline)
    mdline = ("| Overlay Transport Network Name |  |")
    markdown_script.append(mdline)
    mdline = ("| VLAN Transport Zone Name |  |")
    markdown_script.append(mdline)
    mdline = ("| VLAN Transport Network Name |  |")
    markdown_script.append(mdline)
    mdline = ("")
    markdown_script.append(mdline)
    mdline = ("## SDDC Manager Specs")
    markdown_script.append(mdline)
    mdline = ("| Parameter | Configured Value |")
    markdown_script.append(mdline)
    mdline = ("|-----------|------------------|")
    markdown_script.append(mdline)
    mdline = ("| Netmask   |  |")
    markdown_script.append(mdline)
    mdline = ("")
    markdown_script.append(mdline)
    mdline = ("## VSAN Specs")
    markdown_script.append(mdline)
    mdline = ("| Parameter | Configured Value |")
    markdown_script.append(mdline)
    mdline = ("|-----------|------------------|")
    markdown_script.append(mdline)
    mdline = ("| vSAN Name |  |")
    markdown_script.append(mdline)
    mdline = ("| Datastore Name |  |")
    markdown_script.append(mdline)
    mdline = ("")
    markdown_script.append(mdline)
    mdline = ("## Distributed Virtual Switch Specs")
    markdown_script.append(mdline)
    mdline = ("| Parameter | Configured Value |")
    markdown_script.append(mdline)
    mdline = ("|-----------|------------------|")
    markdown_script.append(mdline)
    mdline = ("| MTU |  |")
    markdown_script.append(mdline)
    mdline = ("| VSAN Traffic Type |  |")
    markdown_script.append(mdline)
    mdline = ("| VMOTION Traffic Type |  |")
    markdown_script.append(mdline)
    mdline = ("| VDP Traffic Type |  |")
    markdown_script.append(mdline)
    mdline = ("| VIRTUALMACHINE Traffic Type |  |")
    markdown_script.append(mdline)
    mdline = ("| MANAGEMENT Traffic Type |  |")
    markdown_script.append(mdline)
    mdline = ("| NFS Traffic Type |  |")
    markdown_script.append(mdline)
    mdline = ("| HBR Traffic Type |  |")
    markdown_script.append(mdline)
    mdline = ("| FAULTTOLERANCE Traffic Type |  |")
    markdown_script.append(mdline)
    mdline = ("| ISCSI Traffic Type |  |")
    markdown_script.append(mdline)
    mdline = ("| DVS Name |  |")
    markdown_script.append(mdline)
    mdline = ("| vmnics |  |")
    markdown_script.append(mdline)
    mdline = ("| Networks |  |")
    markdown_script.append(mdline)
    mdline = ("")
    markdown_script.append(mdline)
    mdline = ("## ESXi Cluster Specs")
    markdown_script.append(mdline)
    mdline = ("| Parameter | Configured Value |")
    markdown_script.append(mdline)
    mdline = ("|-----------|------------------|")
    markdown_script.append(mdline)
    mdline = ("| Cluster Name |  |")
    markdown_script.append(mdline)
    mdline = ("| Cluster EVC Mode |  |")
    markdown_script.append(mdline)
    # Loop through these
    mdline = ("| Resource Pool Specs: |  |")
    markdown_script.append(mdline)
    mdline = ("| Name |  |")
    markdown_script.append(mdline)
    mdline = ("| Type |  |")
    markdown_script.append(mdline)
    mdline = ("| CPU Shares Level |  |")
    markdown_script.append(mdline)
    mdline = ("| CPU Shares Value |  |")
    markdown_script.append(mdline)
    mdline = ("| CPU Limit |  |")
    markdown_script.append(mdline)
    mdline = ("| CPU Reservation Percentage |  |")
    markdown_script.append(mdline)
    mdline = ("| CPU Reservation Expandable |  |")
    markdown_script.append(mdline)
    mdline = ("| Memory Shares Level |  |")
    markdown_script.append(mdline)
    mdline = ("| Memory Shares Value |  |")
    markdown_script.append(mdline)
    mdline = ("| Memory Limit |  |")
    markdown_script.append(mdline)
    mdline = ("| Memery Reservation Percentage |  |")
    markdown_script.append(mdline)
    mdline = ("| Memory Reservation Expandable |  |")
    markdown_script.append(mdline)
    # End loop
    mdline = ("")
    markdown_script.append(mdline)
    mdline = ("## Platform Services Controller Specs")
    markdown_script.append(mdline)
    mdline = ("| Parameter | Configured Value |")
    markdown_script.append(mdline)
    mdline = ("|-----------|------------------|")
    markdown_script.append(mdline)
    mdline = ("| PSC ID |  |")
    markdown_script.append(mdline)
    mdline = ("| SSO Domain |  |")
    markdown_script.append(mdline)
    mdline = ("")
    markdown_script.append(mdline)
    mdline = ("## vCenter Spec")
    markdown_script.append(mdline)
    mdline = ("| Parameter | Configured Value |")
    markdown_script.append(mdline)
    mdline = ("|-----------|------------------|")
    markdown_script.append(mdline)
    mdline = ("| VM Size |  |")
    markdown_script.append(mdline)
    mdline = ("")
    markdown_script.append(mdline)
    # Loop through these
    mdline = ("## ESXi Host Specs")
    markdown_script.append(mdline)
    mdline = ("| Server ID | Hostname | Association | vSwitch | Subnet Mask | CIDR | Gateway | IP Address |")
    markdown_script.append(mdline)
    mdline = ("|-----------|----------|-------------|---------|-------------|------|---------|------------|")
    markdown_script.append(mdline)
    mdline = ("|  |  |  |  |  |  |  |  |")
    markdown_script.append(mdline)
    return markdown_script